# Generated by Django 6.0.6 on 2026-06-17 19:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConjuntoPalco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Conjunto')),
                ('quantidade_placas', models.PositiveIntegerField(help_text='Quantas placas formam este conjunto (máx. 30)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Número de Placas')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('em_uso', 'Em Uso'), ('manutencao', 'Em Manutenção')], default='disponivel', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Conjunto de Palco/Piso',
                'verbose_name_plural': 'Conjuntos de Palco/Piso',
                'ordering': ['quantidade_placas'],
            },
        ),
        migrations.CreateModel(
            name='Tenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('tamanho', models.CharField(choices=[('3x3', '3x3 m'), ('4x4', '4x4 m'), ('5x5', '5x5 m'), ('6x6', '6x6 m'), ('7x7', '7x7 m'), ('8x8', '8x8 m'), ('10x10', '10x10 m')], max_length=10, verbose_name='Tamanho')),
                ('tipo', models.CharField(choices=[('piramidal', 'Piramidal'), ('chapeu_bruxa', 'Chapéu de Bruxa')], default='piramidal', max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('em_uso', 'Em Uso'), ('manutencao', 'Em Manutenção')], default='disponivel', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Tenda',
                'verbose_name_plural': 'Tendas',
                'ordering': ['tamanho', 'tipo', 'codigo'],
            },
        ),
    ]
