# Generated by Django 6.0.6 on 2026-06-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Evento')),
                ('cliente', models.CharField(max_length=200, verbose_name='Cliente / Responsável')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('local', models.CharField(max_length=300, verbose_name='Local / Endereço')),
                ('cidade', models.CharField(default='Formosa', max_length=100, verbose_name='Cidade')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Fim')),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='agendado', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('conjuntos', models.ManyToManyField(blank=True, related_name='eventos', to='inventario.conjuntopalco', verbose_name='Conjuntos de Palco/Piso')),
                ('tendas', models.ManyToManyField(blank=True, related_name='eventos', to='inventario.tenda', verbose_name='Tendas')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
